config/routes.rb
Rails.application.routes.draw do
  resources :coffee_reviews
  root 'home#index'
  resources :searches
  resources :coffees
  devise_for :users
  get 'users/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee.rb
class Coffee < ApplicationRecord
    has_one_attached :image 
    has_many :coffee_review, -> { order "created_at DESC"}
    # validates :title, :description, :price, :restaurant => true
    validates :description, length: { minimum: 10 }
    validates :title, :restaurant, length: { minimum: 2 }
    validates :price, numericality: { only_integer: true }
end


  

app/models/coffee_review.rb
class CoffeeReview < ApplicationRecord
    belongs_to :user
end

app/models/concerns/search.rb
class Search < ActiveRecord::Base
    
  def search_coffees
    
    coffees = Coffee.all
    
    coffees = coffees.where(["title LIKE ?","%#{keywords}%"]) if keywords.present?
    coffees = coffees.where(["price >= ?", min_price]) if min_price.present?
    coffees = coffees.where(["price <= ?", max_price]) if max_price.present?
    
    return coffees
    
  end    
end

app/models/search.rb
class Search < ApplicationRecord
    
    
  def search_coffee
    
    coffees = Coffee.all
    
    coffees = coffees.where(["title LIKE ?", keywords]) if keywords.present?
    #coffees = coffees.where(["price >= ?", min_price]) if min_price.present?
    #coffees = coffees.where(["price <= ?", max_price]) if max_price.present?
    
    return coffees
    
  end    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
    has_one_attached :avatar
    validates :name, presence: true
    validates :age, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :avatar]
        devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :avatar]
    end
    
end

app/controllers/coffee_reviews_controller.rb
class CoffeeReviewsController < ApplicationController
  before_action :set_coffee_review, only: %i[ show edit update destroy ]
    before_action :authenticate_user!
  # GET /coffee_reviews or /coffee_reviews.json
  def index
    @coffee_reviews = CoffeeReview.all
  end

  # GET /coffee_reviews/1 or /coffee_reviews/1.json
  def show
  end

  # GET /coffee_reviews/new
  def new
    @coffee_review = CoffeeReview.new
  end

  # GET /coffee_reviews/1/edit
  def edit
  end

  # POST /coffee_reviews or /coffee_reviews.json
  def create
    @coffee_review = CoffeeReview.new(coffee_review_params)
    @coffee_review.user_id = current_user.id
    respond_to do |format|
      if @coffee_review.save
        #format.html { redirect_to @coffee_review, notice: "Coffee review was successfully created." }
        url = "/coffees/" + @coffee_review.coffee_id.to_s
        format.html { redirect_to url, notice: 'Coffee review was successfully created.' }
        format.json { render :show, status: :created, location: @coffee_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coffee_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_reviews/1 or /coffee_reviews/1.json
  def update
    respond_to do |format|
      if @coffee_review.update(coffee_review_params)
        format.html { redirect_to @coffee_review, notice: "Coffee review was successfully updated." }
        format.json { render :show, status: :ok, location: @coffee_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coffee_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_reviews/1 or /coffee_reviews/1.json
  def destroy
    @coffee_review.destroy
    respond_to do |format|
      format.html { redirect_to coffee_reviews_url, notice: "Coffee review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_review
      @coffee_review = CoffeeReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_review_params
      params.require(:coffee_review).permit(:user_id, :coffee_id, :review)
    end
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: [:show, :edit, :destroy, :update]

  # GET /coffees or /coffees.json
  def index
    @coffees = Coffee.where(["title LIKE ?", "%#{params[:search]}%"])
  end

  # GET /coffees/1 or /coffees/1.json
  def show
      @coffee_review = CoffeeReview.new
  end

  # GET /coffees/new
  def new
    @coffee = Coffee.new
  end

  # GET /coffees/1/edit
  def edit
  end

  # POST /coffees or /coffees.json
  def create
    @coffee = Coffee.new(coffee_params)

    respond_to do |format|
      if @coffee.save
        format.html { redirect_to @coffee, notice: "Coffee was successfully created." }
        format.json { render :show, status: :created, location: @coffee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffees/1 or /coffees/1.json
  def update
    respond_to do |format|
      if @coffee.update(coffee_params)
        format.html { redirect_to @coffee, notice: "Coffee was successfully updated." }
        format.json { render :show, status: :ok, location: @coffee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffees/1 or /coffees/1.json
  def destroy
    @coffee.destroy
    respond_to do |format|
      format.html { redirect_to coffees_url, notice: "Coffee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee
      @coffee = Coffee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_params
      params.require(:coffee).permit(:title, :description, :price, :restaurant, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def show
        @search = Search.find(params[:id])
    end 

    def new 
        @search = Search.new
       
    end

    def create
        @search = Search.create(search_params)
        redirect_to @search
    end
    
    private

    def search_params
        params.require(:search).permit(:name, :type, :region)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_reviews_helper.rb
module CoffeeReviewsHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coffee_reviews/_form.html.erb
<%= form_with(model: coffee_review, local: true) do |form| %>
  <% if coffee_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee_review.errors.count, "error") %> prohibited this coffee_review from being saved:</h2>

      <ul>
        <% coffee_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :coffee_id %>
    <%= form.number_field :coffee_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffee_reviews/edit.html.erb
<h1>Editing Coffee Review</h1>

<%= render 'form', coffee_review: @coffee_review %>

<%= link_to 'Show', @coffee_review %> |
<%= link_to 'Back', coffee_reviews_path %>

app/views/coffee_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffee Reviews</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th>User</th>
      <th>Coffee</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table table-light">
    <% @coffee_reviews.each do |coffee_review| %>
      <tr>
        <td><%= coffee_review.user_id %></td>
        <td><%= coffee_review.coffee_id %></td>
        <td><%= coffee_review.review %></td>
        <td><%= link_to 'Show', coffee_review %></td>
        <td><%= link_to 'Edit', edit_coffee_review_path(coffee_review) %></td>
        <td><%= link_to 'Destroy', coffee_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee Review', new_coffee_review_path, class:"btn btn-dark" %>

app/views/coffee_reviews/new.html.erb
<h1>New Coffee Review</h1>

<%= render 'form', coffee_review: @coffee_review %>

<%= link_to 'Back', coffee_reviews_path %>

app/views/coffee_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @coffee_review.user_id %>
</p>

<p>
  <strong>Coffee:</strong>
  <%= @coffee_review.coffee_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @coffee_review.review %>
</p>

<%= link_to 'Edit', edit_coffee_review_path(@coffee_review) %> |
<%= link_to 'Back', coffee_reviews_path %>

app/views/coffees/_form.html.erb
<%= form_with(model: coffee, local: true) do |form| %>
  <% if coffee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee.errors.count, "error") %> prohibited this coffee from being saved:</h2>

      <ul>
        <% coffee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description, class:"form-control"%>
  </div>

  <div class="field mb-3">
    <%= form.label :price, class:"form-label" %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :restaurant, class:"form-label" %>
    <%= form.text_field :restaurant, class:"form-control" %>
  </div>
  
   <div class="field mb-3">
    <%= form.label :image, class:"form-label" %>
    <%= form.file_field :image, class:"form-control" %>
  </div>
  
  <br></br>
  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/coffees/edit.html.erb
<h1>Editing Coffee</h1>

<%= render 'form', coffee: @coffee %>

<%= link_to 'Show', @coffee %> |
<%= link_to 'Back', coffees_path %>

app/views/coffees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffees</h1>
  
  <%= form_tag coffees_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <% end %>   
  
  <%= link_to "Advanced Search", new_search_path %>

<table class="table table-dark">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table table-light">
    <% @coffees.each do |coffee| %>
      <tr>
        <td><%= coffee.title %></td>
        <td><%= coffee.description %></td>
        <td><%= coffee.price %></td>
        <td><%= coffee.restaurant %></td>
        <td><%= link_to 'Show', coffee %></td>
        <td><%= link_to 'Edit', edit_coffee_path(coffee) %></td>
        <td><%= link_to 'Destroy', coffee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffee', new_coffee_path, class:"btn btn-dark" %>

app/views/coffees/new.html.erb
<h1>New Coffee</h1>

<%= render 'form', coffee: @coffee %>

<%= link_to 'Back', coffees_path %>

app/views/coffees/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Title:</strong>
  <%= @coffee.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coffee.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @coffee.price %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @coffee.restaurant %>
</p>

<p>
   <% if @coffee.image.attached? %>
     <%= image_tag @coffee.image %>
   <% end %>
 </p>
 <h2>Review From</h2>
<%= form_with(model: @coffee_review, local: true) do |form| %>
  <div class= "field">
    <%= form.text_area :review %>
    <%= form.hidden_field :coffee_id, :value => @coffee.id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<h2>Review Coffee List</h2>
<ul>
  <% @coffee.coffee_review.each do |coffee_review| %>
   <li><%= coffee_review.review %>     
    (<i><%= coffee_review.user.name if coffee_review.user %> </i>)</li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_coffee_path(@coffee) %> |
<%= link_to 'Back', coffees_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <%= link_to 'Coffee Review', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Coffee', coffees_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Review', coffee_reviews_path, class:"nav-link" %>
        </li>
        
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, class:"nav-link", method: :delete %>
        </li>
         <li class="nav-item">
            <%= link_to "プロファイル", users_show_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Edit", edit_user_registration_path, class:"nav-link"%>
        </li>
        <% else %>
        <li class="nav-item">
            <%= link_to "サインイン", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "ユーザ登録", new_user_registration_path, class:"nav-link" %>
        </li>
      <% end %>
      
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Coffee Review へようこそ</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Coffee Review</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%= render 'home/header' %>
      
      <div class="container">
        <% if user_signed_in? %>
        <br></br>
        <p>こんにちは、<%= link_to current_user.name, users_show_path %></p>
      <% else %>
          <br></br>
          <p>まだ、ログインしません</p>
      <% end %>
      <hr>
      <%= yield %>
          </div>
     
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>



<!DOCTYPE html>
<html>
  <head>
    <title>ItNihongo3Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     
  </body>
</html>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_with model: @search do |f| %>
    <%= f.label :keywords %>
    <%= f.text_field :keywords %>

    <%= f.label :min_price %>
    <%= f.text_field :min_price %>
    
    <%= f.label :max_price %>
    <%= f.text_field :max_price %>

    <%= f.submit "Search" %>
<% end %>

<p><%= link_to "Back", '/coffees' %></p>

app/views/searches/show.html.erb
<h1>Search Result</h1>

<p><%= link_to 'Back', new_search_path %></p>

<% if @search.search_coffee.empty? %>
  <p>No Records Found</p>
<% else %>
  <% @search.search_coffee.each do |c| %>
    <br>
    
    <div class="div">
        <h1><%= c.title %></h1>
        <p>Price: $<%= c.price %></p>
    </div>
  <% end %>
<% end %> 

app/views/users/show.html.erb
<h1>プロフィール</h1>

<h3>メールアドレス</h3>
<%= @user.email %>  
<h3>名前</h3>
 <%= @user.name %>

 <h3>年齢</h3>
 <%= @user.age %>
 
 <h3>Avatar</h3> 
 <% if @user.avatar.attached? %>
<%= image_tag @user.avatar %>
<% end %>